### ISSUE TITLE
Scripts should work in Powershell 

### ISSUE THREAD

**Issue by ivanderk** [oasp/oasp4j-ide#76]
On Windows, the scripts should work on Powershell as well, principally de console of course, but ideally the remainder of the scripts as well  (so people will be able to customize them within a Powershell environment)

**Comment by may-bee** [comment]
I am looking forward to work with windows 10, which introduced the linux command set to the CLI in the last developer build. Given that, all the OS specific scripting stuff will vanish.

**Comment by maybeec** [comment]
if #82 is merged, you may want to copy the linux scripts `env.sh`, `variables`, `scripts/eclipse-start`, `scripts/environment-project` and create the `variables-customized` file analogously to the properities specified in your `variables-customized.bat`.

Since some weeks, I am using only using the git bash on windows, which comes with a more or less linux simulation giving me all what I need for work. Especially, also support for long paths :)
You can initialize your git bash by calling the `env.sh` script within your git bash with a leading dot:

`. env.sh`

Thus, the exported variables will be injected into your current bash session and you will have a fully functioned IDE bash on windows.

Maybe two questions regarding this

1. I would like to distribute the linux-scripts as well with the windows distribution. Should we simply add the scripts without the create-or-update scripts etc as well with the windows version? Thus, we could make the use of the git bash on windows more comfortable. The only bad here is the redundant variables-customized file.
2. Is there any plan to also release the linux-scripts on maven central? We currently download the latest release from the windows scripts in our automatic IDE installer based on Oomph. However, for linux, the scripts seem not to be released so far.

@themetalone, @hohwille

**Comment by maybeec** [comment]
@ivanderk I think you have experiences with powershell even more than me.
What is breaking compatibility with powershell? Can you provide an appropriate fix soon, such that it can be part of the next scripts release?

**Comment by maybeec** [comment]
As discussed with @ivanderk, we will not release a complete script set for every shell environment.
We provided a console script to run and initialize the powershell, which should be enough.
